version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 80:80
            - 443:443
        #volumes:
        #    - ./conf.d:/etc/nginx/conf.d
        environment:
            - DOMAIN=gaku.gakusmemo.com
            - EMAIL=pro.gaku@gmail.com
            - STAGE=test #test or product
