version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./Dockerfile
        links:
            - wordpress
            - wordpress2
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./conf.d:/etc/nginx/conf.d
    wordpress:
        image: wordpress
        environment:
            WORDPRESS_DB_PASSWORD: example
        links:
            - wordpress-db:mysql
    wordpress-db:
        image: mariadb:10.3.1
        environment:
            MYSQL_ROOT_PASSWORD: example
    wordpress2:
        image: wordpress
        environment:
            WORDPRESS_DB_PASSWORD: example
        links:
            - wordpress-db2:mysql
    wordpress-db2:
        image: mariadb:10.3.1
        environment:
            MYSQL_ROOT_PASSWORD: example
